# Replace with own URL
webhookURLs:
  - "https://discord.com/api/webhooks/XXXXXX"
relayChatOnlyToFirstWebhook: true
announceServerStatus: true
batchWindowSeconds: 28800
permaShush: false
relayAdvancements: true
easterEggDiamondHoe: false
easterEggDragonKill: false
easterEggCreeperPowered: false
ignoredPlayers:
  - NAMESHERETOIGNORE