# Replace with own URL
webhookURL: "https://discord.com/api/webhooks/XXXXXX"
announceServerStatus: true
batchWindowSeconds: 28800
permaShush: false
relayAdvancements: true
easterEggDiamondHoe: false
easterEggDragonKill: false
easterEggCreeperPowered: false
ignoredPlayers:
  - NAMESHERETOIGNORE